### ISSUE TITLE
[FEATURE REQUEST] Scanning alternate source for Media...?

### ISSUE THREAD

**Issue by Astara** [JerloPH/HomeCinema#10]
I thought I'd try my anime lib ... about 17875 ".mkv" extensions found, but don't know how many HC will find in IMDB as most are not movies.

Usually, a quick search of wikipedia is the best place to pick up references to anime.  

A good site for anime might be https://anidb.net/.  Wikipedia, also often has commentary, but not 

Sigh...it finished found alot of files, but they are all generic pictures for MPC-HC: Media Player Classic - Home Cinema.
Less than 5-10% seem to have actual pictures

Oh well -- anyway -- just a suggest if you wanted expand the vids you supported.

Thanks for 'listening'....

**Comment by JerloPH** [comment]
I plan to add Anilist search support, once I found a good C# wrapper for it.

I wouldn't be able to do it right now, but expect it to be available before 1.x version

**Comment by zumbawumba** [comment]
@JerloPH 

> ...?

Instead of using the term "Media" here, I suggest you use the term "video assets" or "series assets" or "media assets", or "media data" or such.

"Media" has a very wide meaning, and thus is rather ambiguous when used in such cases. For example, in HC under Settings>File, the term "Media Locations" is used, which in that case means the location of those video files.

In other words, it helps to be consistent and specific with the terms HC uses, in ways the common user can understand without too much ambiguity.

Furthermore, I also suggest that you change the term "Media Locations" to "Video File Locations", and "Series Locations" to "Series Folder Locations". In fact, you could be even more clear by using "Video File Locations (e.g. movies)" and "Series Folder Locations (i.e. for TV series and the like)".

**Comment by Astara** [comment]
@zumbawumba - how does your comment relate to where to search for Media pictures of anime?  This isn't about any terms used in the program.  Please try to understand what is being discussed before commenting on the wording choice used in the discussion.   The discussion is not about files or folders but about reference sources.

**Comment by JerloPH** [comment]
@zumbawumba 
I will take that into consideration and make a clear hint as to what the App expects from the user to provide. Tho, this discussion is for another issue, not here since the issue is regarding sources to pull info from.

@Astara 
I think he only mean to have clarity and distinction as to what to call the related 'Settings'. I agree that is a discussion for a separate issue, but the way you corrected him is not ToS-friendly, so to speak. 

To update on your issue, I already have it planned in my To-do list. I just haven't tried it yet and if you can provide a good C# wrapper for Anilist, MAL, or whatever Anime source is good, I would greatly appreciate it.

**Comment by Astara** [comment]
@JerloPH  -- I've updated my comment to be, I hope, more appropriate.  

As for your update, I think I sorta got that status from earlier comments.

As for wrappers -- I'm not familiar with any wrappers for those sources, let alone an open-source wrapper in any specific language, let alone a specific language that may not be common in open-source projects.

I'm not that familiar with C#, but does it even have an open source compiler + ecosystem where someone from, say, linux or such might be able to recompile and work with C# sources and produce a product suitable for multiple opensource platforms?

I've found less availability of compatibility libraries and wrappers for open-source projects since such libraries and wrappers don't seem to attract open-source developers (sigh)...

p.s. -- For whatever reason(s), I find wikipedia to be a better source for me to look up the anime I watch in.  It's easier for me to search for and usually has good story synapses, vs. a source like anidb, doesn't usually have a complete a description of what happens in the anime (oft, I believe, out of a concern for relating "spoilers" -- not an issue for me, so I find that withholding to be something lacking for me).

**Comment by zumbawumba** [comment]
@Astara 

> how does your comment relate to where to search for Media pictures of anime?

Well, is not everything related? I tend to think so, as with that precedent. If you don't agree, then that's fine by me.

> I'm sorry, but correcting our usage of common words in our conversations doesn't helpful. 

No need to feel sorry, as much things people say are "doesn't helpful". Regardless, my initial focus was not your "conversations", but rather just the title of this post, of which I had mistakenly thought JerloPH had made. As you can see in my comment, I addressed JerloPH, with no mention of you. Point being, if I had known you wrote that, then I never would have commented, as I didn't want to have a conversation with you, and I still don't. But that's of no fault of yours, but rather, I tend to only communicate with those who can do so with the highest of standards.  

> This isn't about any terms used in the program. 

Right or wrong, "this" is whatever we agree to make it, that is unless what you proclaim is the only thing that matters here.

> Before you try to correct peoples' usage of various terms, you might want to understand what they are talking about. We are NOT talking about files or folders, but reference sources.

I wasn't correcting anyone with my comment, as it was just a suggestion, of which I took the time to explain with an example. If that confused and/or upset you, then I understand, as we all make mistakes sometimes.

Why do you assume I didn't understand what you wrote? Sure, some of it was rather questionable and perhaps vexing ( e.g. "just a suggest if you wanted expand the vids you supported"), but I was still able to get the overall gist of it without getting too confused. But no matter, as most of what you wrote is of little interest to me.

But thanks for trying to explain this all to me, as I find this all very educational and entertaining.

That said, no need to reply to me, as I'm now 100% done with this project, as I have more important things not to do.

**Comment by Astara** [comment]
> @Astara
> > how does your comment relate to where to search for Media pictures of anime?
---
It didn't.  Admittedly it was not my place to respond as I did.

> if I had known you wrote that, then I never would have commented, as I didn't want to have a conversation with you, and I still don't. But that's of no fault of yours, but rather, I tend to only communicate with those who can do so with the highest of standards.
----
I'm sorry I got in the way, please don't let me stop you, as I'm not even part of this project, other than by happenstance in being a user.  I'm usually too afraid to post code as usually don't feel confident enough.

> I wasn't correcting anyone with my comment, as it was just a suggestion, of which I took the time to explain with an example. If that confused and/or upset you, then I understand, as we all make mistakes sometimes.
---
I often make mistakes -- indeed, often more than others.  Though in my own work, in addition to making
many mistakes, I also make many corrections.  If I had any talent in programming it was due to being able
to make mistakes and corrections faster than most, but certainly not due to a lack of mistakes.

> But thanks for trying to explain this all to me, as I find this all very educational and entertaining.
---
Perhaps not as much educational as for me as an example of how not to respond (sigh).

> That said, no need to reply to me, as I'm now 100% done with this project.
Please remember, I'm a passer-by, a user of the updates to MPC:HC, not someone who is part of the project, so don't let my comments dissuade you from posting to others or participating. And sorry my comments were a bit hastily prepared.  Please note, I did try to rephrase my comments, despite them being perhaps too little, too late.

**Comment by JerloPH** [comment]
@Astara This feature is now available on 'dev' branch. You can compile your own to test. Or, wait til this weekend to have access to the Pre-release.

**Comment by JerloPH** [comment]
Feature released on v0.8, will close.
