### ISSUE TITLE
[BUG] There are double apostrophes ('') in the titles where there should be one (').

### ISSUE THREAD

**Issue by zumbawumba** [JerloPH/HomeCinema#11]
Every video file that has an apostrophe in the title, like this:

Mister Magoo's Christmas Carol

Is being indexed in HomeCinema with double apostrophes, like this:

Mister Magoo"s Christmas Carol

Perhaps this is a bug on my end, but all my other software checks fine, and I've never seen such a thing before.

I hope you can duplicate it and fix it. If you need more help/info let me know.

<<<<<<<<<<<<<<<<<<

![double apostrophes bug](https://user-images.githubusercontent.com/86828379/124370136-bc3f4e00-dc28-11eb-8885-1dbc47105558.jpg)

<<<<<<<<<<<<<<<<<<

Windows 10 64 bit (updated) with North American English keyboard setting

HomeCinema v0.7.1.0 r38

**Comment by JerloPH** [comment]
Check the 'name' column on 'info' table on your HomeCinema.db file (You can use SQLite DB Browser).
If its the same as above screenshot, I might have missed something on saving to database.

EDIT: Made change to dev branch that could possibly fix the issue.  I'll create a pre-release build file so make sure to try it.
EDIT 2: Link to pre-release: https://github.com/JerloPH/HomeCinema/releases/tag/alpha-v0.7.1.1

**Comment by zumbawumba** [comment]
I checked with DB Browser for SQLite and the name was the same in HomeCinemaDB.

I then tried your pre-release alpha-v0.7.1.1 and that appears to have fixed the issue.

I'll continue to test HomeCinemaDB and report back as need be.

**Comment by JerloPH** [comment]
Thanks for the feedback!

My theory on that is I've used a method to sanitize the entries so it can be properly inserted into the database. Apostrophe must be doubled in SQL. In the 'dev' branch, I changed this to sanitize only during the insert query. Instead of during the load up screen.

And thanks for rigorously testing. Much appreciated ☺️

**Comment by zumbawumba** [comment]
> I changed this to sanitize only during the insert query.

Sounds good. Furthermore FYI, this appears to have fixed another related issue, where an apostrophe was being removed, like this:

Original filename:
Bob's Fat Cat

Shows up in HC as:
Bobs Fat Cat

Regardless, I just tested for that issue again, and all seems to be fine now.

thanks

**Comment by JerloPH** [comment]
Fixed on dev, not on stable release yet

**Comment by JerloPH** [comment]
Released fix on v0.7.2
