### ISSUE TITLE
[FEATURE REQUEST] consolidated toolbar area

### ISSUE THREAD

**Issue by zumbawumba** [JerloPH/HomeCinema#13]
This is just some UI stuff for you to consider for down the road.

My main UI suggestion is to have all control buttons in a slim, consolidated toolbar area, still with no icons as it is now, but whatever, as I know many folks love icons.

This could be an option or a change, but that's no matter to me.

I'm in no great hurry to see this done soon at all, rather, I just thought you should think about it now before HC evolves into something that would make it much harder to do later. In other words, I'm fine with you giving this a very low priority. In fact, I'm willing to do what I can to make a new UI for HC, but I'll need to learn more, but I'm game.

Here's some mockups I did of what I'm thinking about, which include some other features you can ignore for now:

![UI 1](https://user-images.githubusercontent.com/86828379/124531903-5091e800-ddc4-11eb-9069-d3b7ecac23e4.png)
![UI 2](https://user-images.githubusercontent.com/86828379/124531911-55569c00-ddc4-11eb-8c74-13ebbc4cc98e.png)
![UI 3](https://user-images.githubusercontent.com/86828379/124531915-58518c80-ddc4-11eb-94a2-829111c5f962.png)

I'm also thinking that the search options area in HC (as it is now), could perhaps be a drop-down toolbar, and perhaps within that, have another drop-down toolbar for more advanced searches.

**Comment by JerloPH** [comment]
1. I'll consider the consolidated toolbar idea, though I'd add it to the bottom list for now.
2. The UI mockup is great! I'll plan to add that kind of right-click menu when I've added support to Anilist search (for Anime entries).

**Comment by zumbawumba** [comment]
Thanks for considering this superfluous proposal.

As for right-click searches, I reckon the more you can use those, then the less is needed to load the database up with more work and whatnot. Same goes for pointing to folders, as you know.

**Comment by JerloPH** [comment]
I'm gonna open this for now since its not implemented yet.

For future reference, leave closing issues to me. Thanks!

**Comment by zumbawumba** [comment]
Okay. 👌

Also, here's a mockup of a drop-down menu for the search options, which is not far off from what you have now.

Closed:

![drop-down search menu 1](https://user-images.githubusercontent.com/86828379/125002565-1d409a80-e00a-11eb-8a76-ace9802dab50.jpg)

Opened:

![drop-down search menu 2](https://user-images.githubusercontent.com/86828379/125002572-216cb800-e00a-11eb-9565-331eb3f51100.jpg)

I imagine something like that is perhaps the easiest way to consolidate the toolbar area.

**Comment by JerloPH** [comment]
Feature is now on 'dev' branch. Wait for Pre-release to test the changes.

**Comment by JerloPH** [comment]
Feature released on v0.8, will close.
