### ISSUE TITLE
[FEATURE REQUEST] Confirmation alert to Cancel reloading

### ISSUE THREAD

**Issue by Neraps** [JerloPH/HomeCinema#9]
Hi Jerlo. Thanks for this app. I find it works well with a small library, however if I accidentally click on the top level of a large collection(spanning a few years) it sits on the "Loading Collections" with no way to cancel that action to change the setting. The only way out is to End Task the app and then on restarting it just does the same thing. Is it possible to set it so the Loading dialogue box can be Cancelled/Stop without shutting down the whole program and thereby allowing changes to the settings etc.??

**Comment by JerloPH** [comment]
Thanks for the feedback!

If I understand this correctly, you want a setting that can make confirmation alerts so you can cancel the reloading of the Listview items, correct?

If so, this will be done in the next release.

**Comment by Neraps** [comment]
That would work. Thanks Jerlo!.
Keep up the good work!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JerloPH** [comment]
New release addressing the issue. Will close now.

**Comment by Neraps** [comment]
Great I will check it out. 👍

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
